FROM ubuntu:22.04 AS python_build

# Stage 1: Build the Python environment
# Use a Node.js base image that has build tools for both languages
FROM node:18-bullseye-slim AS build

# Start from the Miniconda base image
FROM continuumio/miniconda3

# Set the anaconda working directory
WORKDIR /app/conda_scripts

#Run all of the anaconda installs
RUN conda create --name rag_env python=3.12 -y && \
    conda activate rag_env&& \
    conda install pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia -y&& \
    conda install -c conda-forge faiss-gpu

# Set the working directory for the Python script
WORKDIR /app/python_scripts

# Run all of the pip installs
RUN pip install transformers && \
    pip install accelerate && \
    pip install langchain langchain_community && \
    pip install pypdf && \
    pip install peft && \
    pip install bitsandbytes>=0.43.0 --prefer-binary && \
    pip install sentence-transformers

# Make the new environment the default when the container starts
# This adds the necessary activation steps to the shell login
RUN echo "conda activate rag_env" > /etc/profile.d/conda_activate.sh

# Install any non-conda packages with pip (if necessary)
# RUN /opt/conda/envs/my_env/bin/pip install my-pip-package

# Stage 2: Build the Node.js application
FROM node:18-bullseye-slim AS final

# Set the working directory for the Node.js app
WORKDIR /app

# Copy the Node.js files
COPY package.json package-lock.json ./
RUN npm install --production

# Copy the Node.js API and the Python scripts from the build stage
COPY . .
COPY --from=build /app/python_scripts /app/python_scripts
RUN find /app/python_scripts -type l ! -exec test -e {} \; -print

# Expose the port your Node.js API listens on
EXPOSE 3000

# Command to run the Node.js API
CMD ["node", "index.js"]